name: clang-format

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: '.'
        exclude: './deps'
        extensions: 'h,c'
        clangFormatVersion: 20
        style: file
        assumeFilename: 'file.c'
