name: clang-format

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format-20
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-20

    - name: Check formatting
      run: |
        # Check if files are properly formatted
        ./format.sh --check || (echo "Files are not properly formatted. Run './format.sh' to fix." && exit 1)
