name: clang-format Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        exclude: './deps'
        extensions: 'h,c'
        clangFormatVersion: 11
        style: file
