name: Unit Tests on MacOS Big Sur 11.0

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true
      - name: Run Makefile
        run: make test
