name: Unit Tests on MacOS Catalina 10.15

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true
      - name: Run Makefile
        run: make test
